version: "3.8"
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=TEST@123
      - MYSQL_DATABASE=MYdb
    volumes:
      - bankapp-volume:/var/lib/mysql 
    networks:  
      - bankapp
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  bankapp:
    image: rk0617/bank-app:latest
    container_name: bankapp 
    networks:  
      - bankapp
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/MYdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_PASSWORD=TEST@123 
    ports:
      - 8080:8080  
    depends_on:
      mysql: 
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
networks:
  bankapp:

volumes:
    bankapp-volume:
