apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bankapp-deployment 
  namespace: bankapp 
  labels:
    app: bankapp-deploy 
spec: 
  replicas: 2 
  selector:
    matchLabels:
      app: bankapp-deploy
  template:
    metadata:
      labels:
        app: bankapp-deploy 
    spec: 
      containers:
      - name: bankapp 
        image: rk0617/bankapp:latest 
        ports:
        - containerPort: 8080 
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: SPRING_DATASOURCE_URL 
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: config-map
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: banksecret
              key: SPRING_DATASOURCE_PASSWORD
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---

apiVersion: v1
kind: Service 
metadata:
  name: bankapp-service 
  namespace: bankapp
  labels:
    app: bankapp-svc 
spec:
  selector:
    app: bankapp-deploy
  type: NodePort 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080