apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mysql-deployment
  labels: 
    app: mysql-deploy 
  namespace: bankapp 

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: mysql-deploy 
  template: 
   metadata:
      labels:
        app: mysql-deploy    
  spec:
    containers:
    - name: mysql-deployment-container
      image: mysql:latest
      ports:  
      - containerPort: 3306 
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: banksecret
          key: MYSQL_ROOT_PASSWORD
    - name: MYSQL_DATABASE
      valueFrom:
        configMapRef:
          name: config-map
          key: MYSQL_DATABASE
    volumeMounts:
    - name: mysql-pv-storage
      mountPath: /var/lib/mysql 
      subPath: mysql-data 
  volumes: 
  - name: mysql-pv-storage 
    persistentVolumeClaim:
      claimName: mysql-pvc

--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: mysql-service 
  namespace: bankapp
  labels: 
    app: mysql-deploy 

spec:
  selector:
   app: mysql-deploy 
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

