kind: Deployment 
apiVersion: apps/v1 
metadata:
  labels:
    app: bankapp-deploy
  name: bankapp-deploy 
  namespace: bankapp-ns
spec: 
  replicas: 3 
  selector:
    matchLabels:
      app: bankapp-deploy 
  template:
    metadata:
      name: bankapp-deploy
      labels:
        app: bankapp-deploy
    spec:
      containers:
        - name: bankapplication 
          image: rk0617/bankapp:latest 
          ports: 
            - containerPort: 8080 
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL 
                  name: myconfig
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom: 
                configMapKeyRef:
                  key: SPRING_DATASOURCE_USERNAME 
                  name: myconfig
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: myconfig

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_PASSWORD 
                  name: secrets  

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits: 
              memory: "1Gi"
              cpu: "500m"