kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2
metadata:
  name: bankapp-hpa 
  namespace: bankapp-ns 
spec: 
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: bankapp-deploy
    namespace: bankapp-ns
  minReplicas: 1 
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu 
        target:
          type: Utilization
          averageUtilization: 10 