kind: StatefulSet 
apiVersion: apps/v1 
metadata:
  name: mysql
  labels:
    app: mysql 
  namespace: bankapp-ns 
spec: 
  serviceName: mysql-headless
  replicas: 3
  selector:
    matchLabels:
      app: mysql 
  template:
    metadata:
      name: mysql 
      labels: 
        app: mysql 
    spec:
      containers:
        - name: mysql-container
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: secrets 
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: myconfig
      volumes: 
        - name: mysql-data 
          persistentVolumeClaim:
            claimName: mysql-pvc


