apiVersion: v1 
kind: Service
metadata: 
  labels:
    app: bankapp-service
  name: bankapp-service
  namespace: bankapp-ns 
spec:
  selector:
    app: bankapp-deploy
  type: NodePort 
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 8080