apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bankapp-deploy
  namespace: bankapp-ns
  labels:
    app:  bankapp-deploy
spec:
  selector:
    matchLabels:
      app: bankapp-deploy
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  bankapp-deploy
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  bankapp-deploy
        image:  rk0617/bankapp:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi 
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: bankapp-deploy
              key: DB_HOST
        ports:
        - containerPort:  80
          name:  bankapp-deploy 
      restartPolicy: Always