apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deploy
  namespace: bankapp-ns
  labels:
    app: bankapp-deploy
spec:
  selector:
    matchLabels:
      app: bankapp-deploy
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bankapp-deploy
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nc -z mysql-0.mysql-service 3306; do echo waiting for mysql; sleep 2; done"
            ]
      containers:
        - name: bankapp-deploy
          image: rk0617/bankapp:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: SPRING_DATASOURCE_USERNAME
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: MYSQL_DATABASE
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: SPRING_DATASOURCE_PASSWORD