apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: bankapp-ns
spec:
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
  serviceName: mysql-service
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306 
        volumeMounts:
        - name: mysql-pv-storage
          mountPath: /var/lib/mysql
          subPath: mysql-data
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret 
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: configmap 
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
      namespace: bankapp-ns
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: manual
      resources:
        requests:
          storage: 10Gi