apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: mysql-pv 
  namespace: bankapp-ns 
  labels:
    app: mysql-pv 
spec:
  capacity:
    storage: 10Gi
  accessModes: 
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: manual 
  hostPath:
    path: /mnt/data/mysql
    type: DirectoryOrCreate