apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: bank-ns
  labels:
    app: mysql-svc
spec:
  clusterIP: None  # <- This makes it truly headless
  selector:
    app: mysql-std  # <- Make sure this matches your StatefulSet pod label
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306


# kubectl apply -f namespace.yml -f config-map.yml -f secretes.yml -f pv.yml -f pvc.yml
# kubectl apply -f mysql-stateful.yml -f mysql-service.yml -f bankapp-deployment.yml -f bankapp-service.yml