apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: bank-ns
  labels:
    app: mysql-std
spec:
  serviceName: mysql-headless
  replicas: 2
  selector:
    matchLabels:
      app: mysql-deploy
  template:
    metadata:
      labels:
        app: mysql-deploy
    spec:
      containers:
        - name: mysql-cont
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banksecrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: bankconfig
                  key: MYSQL_DATABASE
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi


---

apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: bank-ns
  labels:
    app: mysql-svc
spec:
  clusterIP: None   
  selector:
    app: mysql-deploy   
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
