apiVersion: apps/v1 
kind: StatefulSet 
metadata: 
  name: mysql-std
  namespace: bank-ns 
  labels:
    app: mysql-std
spec:
  serviceName: mysql-service
  replicas: 2
  selector:
    matchLabels:
      app: mysql-deploy
  template:
    metadata:
      labels:
        app: mysql-deploy
    spec:
      containers:
        - name: mysql 
          image: mysql:latest 
          ports:
            - containerPort: 3306 
          env: 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: banksecrets
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: bankconfig
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
      name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi